apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: medici/bootstorage
    context: k8s-ambassador-storage
  - image: medici/shop
    context: k8s-ambassador-shop
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes/pv.yaml
    - ./kubernetes/redis.yaml
    - ./kubernetes/bootstorage.yaml
    - ./kubernetes/shop.yaml
    - ./kubernetes/cronjob.yaml
profiles:
- name: james, dev, kubernetes, ambassador
  build:
    local:
      push: false