apiVersion: v1
kind: Service
metadata:
  name: oauth2
  labels:
    app: oauth2
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: token-granter_mapping
      prefix: /saas/
      service: oauth2:8080
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: oauth2
  type: ClusterIP
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: oauth2
  name: oauth2
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: oauth2
  template: 
    metadata: 
      labels: 
        app: oauth2
    spec: 
      containers: 
        - name: oauth2
          image: medici/oauth2
          imagePullPolicy: Never
          ports: 
            - containerPort: 8080
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: config-ouath2 
data:
  DATABASE_NAME: "ambassadorsaas"
---