---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: bootstorage-svc
  name: bootstorage-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: bootstorage-svc
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: bootstorage-svc
  name: bootstorage-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bootstorage-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: bootstorage-svc
    spec:
      containers:
      - image: medici/bootstorage
        imagePullPolicy: Never
        name: bootstorage-svc
        env:
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: bootstorage-env
                key: redis_host
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: bootstorage-env
                key: redis_port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bootstorage-env
                key: redis_password
---
apiVersion: v1
kind: Secret
metadata:
  name: bootstorage-env
type: Opaque
data:
  redis_password: Y2FsY3VsYXRvcg==
stringData:
  redis_host: redis
  redis_port: '6379'