---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: bootstorage-svc
  name: bootstorage-svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: bootstorage-svc_mapping
      prefix: /store/
      service: bootstorage-svc:5000
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: bootstorage-svc
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: bootstorage-svc
  name: bootstorage-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bootstorage-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: bootstorage-svc
    spec:
      containers:
      - image: medici/bootstorage
        imagePullPolicy: Never
        name: bootstorage-svc
        env:
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: secret-env
                key: redis_host
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: secret-env
                key: redis_port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-env
                key: redis_password