apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cronjob
        spec:
          containers:
          - name: cronjob
            image: spotify/alpine:latest
            imagePullPolicy: Always
            command:
            - curl
            args:
            - http://bootstorage-svc:5000/bootstorage/deletelru
          restartPolicy: Never  
  schedule: '*/40 * * * *'
  successfulJobsHistoryLimit: 5