kind: PersistentVolume
apiVersion: v1
metadata:
  name: calculator-volume
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "pvdata"